version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    depends_on:
      - mysql
      - redis
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./boomerang:/var/www/html
    ports:
      - "8000:80"
    command: >
      bash -c "
      apt update && 
      apt install -y less && 
      curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && 
      chmod +x wp-cli.phar && 
      mv wp-cli.phar /usr/local/bin/wp && 
      docker-entrypoint.sh apache2-foreground"

  nginx:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  db_data:
  wordpress_data:
  redis_data: